project_name         = "redux-project"
project_environment  = "development"
region               = "us-east-1"
owner                = "Anitta"
bits                 = 4
wp_cidr_block        = "10.0.0.0/16"
db_cidr_block        = "10.1.0.0/16"
lb_sg_ports          = ["80", "443"]
wp_sg_ports          = ["80", "443"]
db_sg_ports          = ["3306"]
domain_name          = "anitta.redux.cloud"
lb_ingress_cidr_ipv4 = "0.0.0.0/0"
lb_egress_cidr_ipv4  = "0.0.0.0/0"
lb_egress_port       = "-1"