---
- name: Install WordPress on LEMP Stack
  hosts: wordpress
  become: true
  vars:
    wp_db_name: "{{ db_name }}"
    wp_db_user: "{{ db_user }}"
    wp_db_password: "{{ db_pass }}"
    wp_db_host: "{{ db_host }}"

  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install required packages
      yum:
        name:
          - nginx
          - mysql
          - php-fpm
          - php-mysqlnd
          - unzip
          - wget
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set ownership for WordPress files
      file:
        path: /var/www/html/wordpress
        owner: nginx
        group: nginx
        mode: "0755"
        recurse: yes

    - name: Configure wp-config.php
      template:
        src: templates/wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
        owner: nginx
        group: nginx
        mode: "0644"

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
