---
- name: Install and Configure WordPress on LEMP Stack
  hosts: wordpress
  become: true
  vars:
    wp_db_name: "{{ db_name }}"
    wp_db_user: "{{ db_user }}"
    wp_db_password: "{{ db_pass }}"
    wp_db_host: "{{ db_host }}"
    efs_id: "{{ efs_id }}"

  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install required packages
      yum:
        name:
          - nginx
          - php-fpm
          - php-mysqlnd
          - php-json
          - php-xml
          - php-gd
          - php-mbstring
          - php-curl
          - unzip
          - wget
          - amazon-efs-utils
          - rsync
        state: present

    - name: Start and enable Nginx & PHP-FPM
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - php-fpm
        - nfs-utils

    - name: Update PHP-FPM user and group
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^user = '
        line: 'user = nginx'

    - name: Update PHP-FPM group
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^group = '
        line: 'group = nginx'

    - name: Restart PHP-FPM to apply changes
      service:
        name: php-fpm
        state: restarted

    - name: Remove default index.html
      file:
        path: /usr/share/nginx/html/index.html
        state: absent

    - name: Configure Nginx for WordPress
      copy:
        dest: /etc/nginx/conf.d/wordpress.conf
        content: |
          server {
              listen 80;
              server_name _;

              root /var/www/html/;
              index index.php index.html index.htm;

              set $https_redirect 0;
              if ($http_x_forwarded_proto = "http") {
                  set $https_redirect 1;
              }

              if ($https_redirect = 1) {
                  return 301 https://$host$request_uri;
              }

              location / {
                  try_files $uri $uri/ /index.php?$args;
              }

              location ~ \.php$ {
                  include fastcgi_params;
                  fastcgi_pass unix:/run/php-fpm/www.sock;
                  fastcgi_index index.php;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  fastcgi_param HTTPS "on";
                  fastcgi_param HTTP_X_FORWARDED_PROTO "https";
              }

              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|eot|mp4|webm)$ {
                  root /var/www/html/;
                  access_log off;
                  expires max;
                  log_not_found off;
              }
          }
      notify: Restart Nginx

    - name: Download WordPress tarball
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress to temporary directory
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: yes
        extra_opts:
          - --strip-components=1

    - name: Copy non-wp-content files to /var/www/html
      command: >
        rsync -a --exclude=wp-content/ /tmp/wordpress/ /var/www/html/

    - name: Ensure local wp-content directory exists (pre-mount)
      file:
        path: /var/www/html/wp-content
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'

    - name: Add EFS mount entry to fstab for wp-content
      lineinfile:
        path: /etc/fstab
        line: "{{ efs_dns_name }}:/ /var/www/html/wp-content nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev 0 0"
        state: present

    - name: Ensure EFS is mounted to wp-content
      command: mount -a
      changed_when: false

    - name: Populate wp-content on EFS with WordPress files
      command: >
        rsync -a /tmp/wordpress/wp-content/ /var/www/html/wp-content/

    - name: Configure wp-config.php
      template:
        src: templates/wp-config.php.j2
        dest: /var/www/html/wp-config.php
        owner: nginx
        group: nginx
        mode: "0644"
      notify: Restart Nginx

    - name: Add .htaccess file for WordPress
      copy:
        dest: /var/www/html/.htaccess
        content: |
          # BEGIN WordPress
          <IfModule mod_rewrite.c>
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.php$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.php [L]
          </IfModule>
          # END WordPress

          <IfModule mod_headers.c>
          Header always set Content-Security-Policy "upgrade-insecure-requests"
          </IfModule>
        owner: nginx
        group: nginx
        mode: "0644"

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted